export const cookiesPolicyDataEn = [
    {
        title: 'What Are Cookies?',
        text: 'Cookies are small text files that are stored on your device (computer, tablet, or mobile) when you visit a website. They are used to remember your preferences, provide personalized experiences, and analyze website traffic. Cookies are essential for the effective operation of our website and to help you shop with us online.',
    },
    {
        title: 'Use of Cookies',
        text: '3mpq Studio uses cookies to understand how our site is used and to improve user experience. Specifically, we use Google Analytics to analyze the performance of our website and understand our audience. Google Analytics cookies collect information in an anonymous form, including the number of visitors to the site, where visitors have come to the site from, and the pages they visited.',
    },
    {
        title: 'Types of Cookies We Use',
        text: `Strictly Necessary Cookies: These are required for the operation of our website. They include, for example, cookies that enable you to log into secure areas.

        Analytical/Performance Cookies: They allow us to recognize and count the number of visitors and see how visitors move around our website. This helps us improve the way our website works, for example, by ensuring users find what they are looking for easily.
        
        Functionality Cookies: These are used to recognize you when you return to our website. This enables us to personalize our content for you and remember your preferences.`,
    },
    {
        title: 'Managing Cookies',
        text: `Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set, visit www.aboutcookies.org or www.allaboutcookies.org.

        Please note that if you choose to disable cookies, it may limit your use of certain features or functions on our website or service.`,
    },
    {
        title: 'Google Analytics',
        text: `Our website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help us analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google.

        For more information on Google Analytics cookies, visit the official Google Analytics page.`,
    },
    {
        title: 'Your Consent',
        text: 'By using our website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.',
    },
    {
        title: 'Contact Us',
        text: 'If you have any questions about our Cookie Policy, please contact us.',
    },
]

export const cookiesPolicyDataUa = [
    {
        title: 'Що таке файли cookie?',
        text: 'Файли cookie — це невеликі текстові файли, які зберігаються на вашому пристрої (комп’ютері, планшеті чи мобільному телефоні), коли ви відвідуєте веб-сайт. Вони використовуються для запам’ятовування ваших уподобань, надання персоналізованого досвіду та аналізу відвідуваності веб-сайту. Файли cookie необхідні для ефективної роботи нашого веб-сайту та для того, щоб допомогти вам робити покупки в нас онлайн.',
    },
    {
        title: 'Використання файлів cookie',
        text: '3mpq Studio використовує файли cookie, щоб зрозуміти, як використовується наш сайт, і покращити взаємодію з користувачем. Зокрема, ми використовуємо Google Analytics для аналізу ефективності нашого веб-сайту та розуміння нашої аудиторії. Файли cookie Google Analytics збирають інформацію в анонімній формі, включаючи кількість відвідувачів сайту, звідки відвідувачі перейшли на сайт і сторінки, які вони відвідали.',
    },
    {
        title: 'Типи файлів cookie, які ми використовуємо',
        text: `Суворо необхідні файли cookie: вони потрібні для роботи нашого веб-сайту. Вони включають, наприклад, файли cookie, які дозволяють входити в безпечні зони.

Аналітичні/продуктивні файли cookie: вони дозволяють нам розпізнавати та підраховувати кількість відвідувачів і бачити, як відвідувачі переміщуються нашим веб-сайтом. Це допомагає нам покращити роботу нашого веб-сайту, наприклад, гарантуючи, що користувачі легко знаходять те, що вони шукають.

Функціональні файли cookie: вони використовуються для розпізнавання вас, коли ви повертаєтеся на наш веб-сайт. Це дозволяє нам персоналізувати наш вміст для вас і запам’ятовувати ваші вподобання.`,
    },
    {
        title: 'Керування файлами cookie',
        text: `Більшість веб-браузерів дозволяють певний контроль над більшістю файлів cookie через налаштування браузера. Щоб дізнатися більше про файли cookie, зокрема про те, як побачити, які файли cookie встановлено, відвідайте www.aboutcookies.org або www.allaboutcookies.org.

Зверніть увагу, що якщо ви вирішите вимкнути файли cookie, це може обмежити використання вами певних функцій або функцій на нашому веб-сайті чи в сервісі.`,
    },
    {
        title: 'Google Аналітика',
        text: `Наш веб-сайт використовує Google Analytics, службу веб-аналітики, яку надає Google, Inc. ("Google"). Google Analytics використовує файли cookie, щоб допомогти нам проаналізувати, як користувачі використовують сайт. Інформація, згенерована файлами cookie про ваше використання веб-сайту, буде передана та збережена в Google.

Для отримання додаткової інформації про файли cookie Google Analytics відвідайте офіційну сторінку Google Analytics.`,
    },
    {
        title: 'Ваша згода',
        text: 'Користуючись нашим веб-сайтом, ви погоджуєтеся на обробку даних про вас компанією Google у спосіб і для цілей, викладених вище.',
    },
    {
        title: 'Зв`яжіться з нами',
        text: 'Якщо у вас виникли запитання щодо нашої Політики щодо файлів cookie, зв’яжіться з нами.',
    },
]
